apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-arch-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-arch-test
    app.kubernetes.io/part-of: multi-arch-test
  name: multi-arch-test
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: multi-arch-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: multi-arch-test
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sdouglas1-tenant/multi-arch-test/multi-arch-test@sha256:a92d5c19bc1f64ab85e256679bfc6a6dd0a33769fa5c1cb56f3eff9e08328116
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
