apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-arch-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-arch-test
    app.kubernetes.io/part-of: multi-arch-test
  name: multi-arch-testqnwr
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: multi-arch-test
    weight: null
status: {}
